# language: cpp
# compiler: gcc
# dist: trusty

# before_install:
#   # C++14
#   - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
#   - sudo apt-get update -qq

# install: 
#   # C++14
#   - sudo apt-get install -qq gcc-5 g++-5 mesa-common-dev libxrandr-dev libxcursor-dev libxxf86vm-dev libxinerama-dev
#   - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
#   - g++ --version
#   - g++ main.cpp -o main -std=c++14

# before_script:
#   - gcc -v && g++ -v && cmake --version
#   - mkdir build
#   - cd build
#   - cmake ..
# script: 
#   - make

matrix:
  include:
    # # works on Precise and Trusty
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++-4.9
    #   env:
    #      - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    # # works on Precise and Trusty
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++-5
    #   env:
    #      - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    # # works on Precise and Trusty
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++-6
    #   env:
    #     - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    # # works on Precise and Trusty
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++-7
    #   env:
    #     - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

sudo: false
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - g++-6
    - clang-3.8
install:
  - "[ $CXX = g++ ] && export CXX=g++-6 || true"
  - "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"

before_install:
  - eval "${MATRIX_EVAL}"

install: 
  # C++14
  - g++-5 --version
  - g++-5 main.cpp -o main -std=c++14