language: cpp
compiler: gcc
dist: trusty
branches:
  only: 
    - release

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - mesa-common-dev
    - libxrandr-dev
    - libxcursor-dev
    - libxxf86vm-dev
    - libxinerama-dev

install:
  - "[ $CXX = g++ ] && export CXX=g++-5 || true"
  - "[ $CC = gcc ] && export CC=gcc-5 || true"

script:
  - mkdir build
  - cd build
  - cmake ../
  - make TravisCI

deploy:
  provider: releases
  api_key:
    secure: b7e50ba0d325c91e0801dbc7607cd2d0485b55f4
    file:
      - NgUI-x86_64.AppImage
      - NgUI-x86_64.AppImage.zsync
  skip_cleanup: true
  # on:
  #   repo: <your repository path>
  #   tags: true
