language: cpp
compiler: gcc
dist: trusty
branches:
  only: 
    - release

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - mesa-common-dev
    - libxrandr-dev
    - libxcursor-dev
    - libxxf86vm-dev
    - libxinerama-dev

install:
  - "[ $CXX = g++ ] && export CXX=g++-5 || true"
  - "[ $CC = gcc ] && export CC=gcc-5 || true"

script:
  - mkdir build
  - cd build
  - cmake ../
  - make TravisCI

after_success:
    before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "YOUR GIT USER NAME"
      - git config --local user.email "YOUR GIT USER EMAIL"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
    deploy:
      provider: releases
      api_key: "git: https://github.com/ on DESKTOP-I47QO5K at 19-Thg12-2017 13:51"
      file:
        - NgUI-x86_64.AppImage
        - NgUI-x86_64.AppImage.zsync
      skip_cleanup: true
