language: cpp
compiler: gcc
dist: trusty
branches:
  only: 
    - release

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - mesa-common-dev
    - libxrandr-dev
    - libxcursor-dev
    - libxxf86vm-dev
    - libxinerama-dev

install:
  - "[ $CXX = g++ ] && export CXX=g++-5 || true"
  - "[ $CC = gcc ] && export CC=gcc-5 || true"

script:
  - mkdir build
  - cd build
  - cmake ../
  - make TravisCI