language: cpp
compiler: gcc
dist: trusty

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-5 mesa-common-dev libxrandr-dev libxcursor-dev libxxf86vm-dev libxinerama-dev
  - g++ main.cpp -o main -std=c++14

before_script:
  - gcc -v && g++ -v && cmake --version
  - mkdir build
  - cd build
  - cmake ..
script: 
  - make